### ISSUE TITLE
py3?

### ISSUE THREAD

**Issue by ahed87** [chrismattmann/tika-python#68]
Hi,
was just playing around a bit to see if I could get this working.

Anyway, below is what happend when I tried with py3 and win8.1 64.
The stop point puzzled me, so I thought I just would let you know.
I guess that you only do py2, so this is just if you ever think in terms of py3...

// ahed

(pjava) C:\VIRENVS\pjava\Scripts>pip install tika
Collecting tika
  Downloading tika-1.10.tar.gz
Requirement already satisfied (use --upgrade to upgrade): setuptools in c:\viren
vs\pjava\lib\site-packages (from tika)
Collecting requests (from tika)
  Using cached requests-2.7.0-py2.py3-none-any.whl
Building wheels for collected packages: tika
  Running setup.py bdist_wheel for tika
  Stored in directory: C:\Users\...\AppData\Local\pip\Cache\wheels\f2\68\5
b\3fa52886820037cfb90525f5c44d0788308face211328020d8
Successfully built tika
Installing collected packages: requests, tika
Successfully installed requests-2.7.0 tika-1.10

(pjava) C:\VIRENVS\pjava\Scripts>python
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (In
tel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tika
>>> tika.initVM()
>>> from tika import parser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\VIRENVS\pjava\lib\site-packages\tika\parser.py", line 19, in <module>

    from tika import parse1, callServer, ServerEndpoint
ImportError: cannot import name 'parse1'
>>> from tika import parse1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'parse1'
>>> dir(tika)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__',
'__package__', '__path__', '__spec__', 'initVM']
>>>

**Comment by chrismattmann** [comment]
hi @ahed87 thanks for the bug report. I don't use Python3, no, as you said I use Python2.7.X usually. Any idea what the above error means? I'm not a py3 guy, but for example the error states that it can't find a function in the tika.py module (parse1), that is called by the parser.py module.

**Comment by chrismattmann** [comment]
ping @ahed87

**Comment by macd** [comment]
The immediate error (can't find parse1) can be fixed by doing  relative import in the parser.py
module by using
from .tika import parse1, callServer, ServerEndpoint  # note the dot in front of tika

but there are other 2->3 issues as well.  You can use the 2to3 utility to convert to Python 3, but then you run into a UnicodeDecodeError pretty deep into the http stack.  About as far as I can take it.  Hope it helps.

**Comment by chrismattmann** [comment]
unfortunately no one has provided any PRs and I don't have time to work on this now. If anyone wants to send me a PR I'd appreciate it, but since tika-python works fine in 2.7 and that's what I develop in, going to close this out for now. Please feel free to re-open if someone has a PR to send me.

**Comment by Pehat** [comment]
Hi @chrismattmann . I would be glad to fix it for Python 3, but let me understand first. You repository has no file parser1.py . Where do you import it from? Are there any other packages should be installed first?

**Comment by macd** [comment]
An alternative is to use Pyjnius for Python 3.  This shows how:

https://github.com/macd/dbm_notebooks/blob/master/The%20Genius%20of%20Pyjnius.ipynb
